### ISSUE TITLE
Request for some additional UC module ports

### ISSUE THREAD

**Issue by sbgraphicdesign** [backdrop-contrib/ubercart#166]
I hope this is the correct place for this, but I'm wondering if there's any chance of getting some of the additional UC modules into Backdrop?

In particular I'd be interested in Price Per Role and Recurring Payments

**Comment by laryn** [comment]
You might also try the backdrop-ops/contrib queue:

- https://github.com/backdrop-ops/contrib/issues

**Comment by bugfolder** [comment]
I plan to work on Price Per Role in the coming months.

**Comment by laryn** [comment]
Sounds great @bugfolder -- if you run into any issues remember that you can post in the [Zulip live chat](https://backdrop.zulipchat.com/) or the [Backdrop forum](https://forum.backdropcms.org/), too.

**Comment by sean327** [comment]
Hi folks, it's been a few years but i worked on a bunch of Ubercart contrib modules for D7, even maintained a couple of minor ones. And now i'm starting to migrate some legacy sites to Backdrop, so i'll be contributing patches. Will work for pizza-and-beer level bounties!

It's great that Backdrop exists and i'm excited to finally start working with it for my own projects.

**Comment by laryn** [comment]
Wonderful @sean327!

**Comment by bugfolder** [comment]
A preliminary version of Price per Role is now in Backdrop modules:

https://backdropcms.org/project/uc_price_per_role

Testing and feedback would be most welcome!

**Comment by bugfolder** [comment]
* [UC Price per Role](https://backdropcms.org/project/uc_price_per_role) has now been out for a while and is being used "in the wild."
* UC Recurring Payments and Subscriptions (`uc_recurring`) has a [development version on Github](https://github.com/backdrop-contrib/uc_recurring) but hasn't done an official release yet.

I'm going to close this issue, since further issues with either module would be best addressed in their respective issue queues.
