### ISSUE TITLE
make entity_plus a dependency

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/ubercart#167]
This needs to use entity_plus for the hook: https://github.com/backdrop-contrib/ubercart/blob/1.x-1.x/uc_product/uc_product.info.inc

https://github.com/backdrop-contrib/entity_plus

**Comment by laryn** [comment]
Hmm.. Just tried to enable `entity_plus` on a dev site with `ubercart` installed and get a WSOD.

**Comment by laryn** [comment]
I see... a lot of UC modules still list EMW as a dependency (via Rules) which obviously conflicts. Going to test changing the Rules dependency to E+ and see if things sort out.

**Comment by laryn** [comment]
Bigger project than I was expecting at the moment...

When Rules moves to using E+ then this function pointed out above will need to be changed to `hook_entity_plus_property_info_alter`, right @herbdool?

**Comment by laryn** [comment]
I submitted a PR for Rules that should make it dependent on Entity Plus instead of EMW.
https://github.com/backdrop-contrib/rules/pull/28

If @Graham-72 merges that into Rules. @robertgarrigos I guess we'll need to make a few modifications here to specify the E+ function names and then specify in the next release that it requires beyond whatever version of Rules is released with the changes.

**Comment by laryn** [comment]
@herbdool @robertgarrigos 
Does this look right (when Rules gets updated to depend on Entity Plus)?

**EDIT:**
Looks like I got a little carried away. How does this look instead?
https://github.com/backdrop-contrib/ubercart/compare/1.x-1.x...laryn:EntityPlus?expand=1

**Comment by laryn** [comment]
I thought I was making progress... but when I use the Rules branch that depends on Entity Plus and the commits above for Ubercart, when I try to view the cart or add a product to the cart I see this:

> EntityFieldQueryException: Entity <em class="placeholder">uc_cart_item</em> has no base table. in EntityFieldQuery->propertyQuery() (line 828 of /path/core/modules/entity/entity.query.inc).

Have to set this aside for now but would love to get Ubercart fully functional!

**Comment by laryn** [comment]
It looks like we have a release of Rules that switches from EMW to E+ -- so this issue becomes more urgent as people begin to upgrade Rules... I think we could specify the next release to require `>= Rules 2.1`.

https://github.com/backdrop-contrib/rules/releases/tag/1.x-2.1.0

**Comment by EganSolo** [comment]
Hi Laryn,
Perhaps my emails did not go through. Since I'm new to Github, I just need a nudge in the right direction: how do I download the latest version with these changes in it? Do I go to the code and click on download? I don't have (yet) git installed, so I'm not sure how to grab the latest revised code.

**Comment by laryn** [comment]
@EganSolo I think the changes you made basically mirror this change (look at the diff on screen to verify, and ignore the lines I accidentally moved downwards in the `.info` file): 

https://github.com/backdrop-contrib/ubercart/compare/1.x-1.x...laryn:EntityPlus?expand=1

I'll submit that as a PR here and if @robertgarrigos agrees, he'll merge it in officially.

**Comment by laryn** [comment]
@robertgarrigos I've made a simple PR to use Entity Plus controller instead of EMW. The latest Rules switches dependencies from EMW to Entity Plus, so I've also added a dependency on a recent version of rules.

https://github.com/backdrop-contrib/ubercart/pull/194

**Comment by laryn** [comment]
@robertgarrigos On a site where `rules` got updated, it crashed ubercart and I had to hot swap this branch on the live site and untangle things with EMW and Entity Plus... Found a few places where the ubercart "Entity Plus" branch needed to use `entity_plus_view` instead of `entity_view` so pushed an update to my `entity-plus-167` branch, which also updated the PR linked above automatically.

**Comment by laryn** [comment]
This was merged. If there are any other issues related let's just open new issues.
