### ISSUE TITLE
Views broken on D7 upgrade

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#254]
On a test D7 upgrade, I'm seeing the Ubercart Views are broken:

![ubercart-views-d7-upgrade](https://user-images.githubusercontent.com/871421/113895608-c0291480-978e-11eb-860a-b1b58cdcea94.png)

Example JSON config:

```
{
    "_config_name": "views.view.uc_customers",
    "module": "uc_order"
}
```

**Comment by laryn** [comment]
If you find yourself in this situation, a workaround is to use the Config import functionality at **/admin/config/development/configuration/single** to import the four views manually:

 - https://github.com/backdrop-contrib/ubercart/blob/1.x-3.x/uc_product/config/views.view.uc_products.json
 - https://github.com/backdrop-contrib/ubercart/blob/1.x-3.x/uc_order/config/views.view.uc_customers.json
 - https://github.com/backdrop-contrib/ubercart/blob/1.x-3.x/uc_order/config/views.view.uc_orders.json
 - https://github.com/backdrop-contrib/ubercart/blob/1.x-3.x/uc_order/config/views.view.uc_orders_user.json

**Comment by bugfolder** [comment]
Interesting that those four Views are all defined in code via `hook_views_default_views()`. (So is View `uc_catalog`; did it come through properly?)

One of the preparation steps for a migration is to save all code Views into the database, so that the migration routines can work their magic. Any View whose state is "database overriding code" is so saved; any View that's in its original state is not. My recollection is that Views defined in code and not saved to the db are not properly converted in the migration.

Do you know if the save-to-the-database was done to those four Views before the import?

**Comment by bugfolder** [comment]
OK, I was able to reproduce this, and it seems very likely it happened because the step of saving all Views into the db was not carried out as part of the Drupal site preparation. This is substep 2 of step 5 of the [official upgrade instructions](https://docs.backdropcms.org/documentation/upgrading-from-drupal-7-steps).

This can be done manually by editing and saving all the individual views, or more efficiently with this drush command:
```
drush ev 'foreach (views_get_all_views() as $view) {$view->save();}'
```
(It would kind of be nice if the official instructions included that. There are some rewriting plans.)

This step needs to be done on the Drupal side of the fence, so it can't be carried out once we have Backdrop code in place. We could potentially add a `hook_update_N()` call that checks for broken Views and if they're broken, re-imports them from the module config files, but it's not clear if we could make that happen before update.php makes its complaints about the broken Views.

**Comment by laryn** [comment]
@bugfolder You are probably right about me missing a step. I have done a few upgrades and never needed to do that step before so I think I've just blocked it out in my mind. Oops!

Perhaps we don't need to worry about this since it is a case of user error (not following the instructions) and has a fairly easy fix -- as noted in https://github.com/backdrop-contrib/ubercart/issues/254#issuecomment-815031016
