### ISSUE TITLE
File download autocomplete problem

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#284]
I'm working on a dev site that had a few file downloads via Ubercart and it may need some TLC as things don't seem to be linked up as I was expecting. Noting here until I get a chance to dig deeper.

**Comment by laryn** [comment]
On this particular site I think the upgrade process cleared out some data from the `uc_product_features` table at some point without me realizing it (e.g. when a directory wasn't set right, or something along those lines). I was able to recover that data from a backup.

But I've realized in the meantime that the autocomplete function on `node/##/edit/features/file/add` doesn't seem to be working.

**Comment by bugfolder** [comment]
FWIW, I've got a (locally) working site upgraded from D7 where all the file downloads came over fine.

> But I've realized in the meantime that the autocomplete function on node/##/edit/features/file/add doesn't seem to be working.

It is on my locally upgraded site. Anything suggestive in watchdog?

**Comment by laryn** [comment]
@bugfolder Thanks for the quick response -- I'll do further testing on a fresh install and this site-in-development. It's definitely not working on the site in question and I don't see anything in the watchdog...

**Comment by bugfolder** [comment]
In the process of working on https://github.com/backdrop-contrib/ubercart/issues/286, I found some problems with how uc_file is storing its product settings and a possible issue that would definitely kill file download autocomplete (but not necessarily on upgraded sites, so consistent with what's reported above).

So, on the problematic site, would you check the active config file uc_file.settings.json, and verify that it contains the line

```
    "uc_file_file_mask": "/.*/",
```

Even if it does, I'd like to suggest applying the patch from PR https://github.com/backdrop-contrib/ubercart/pull/289, which addresses various issues with how product settings are saved; then verify and re-save all product settings at admin/store/settings/products, and see if that helps.

**Comment by laryn** [comment]
I applied the patch to a staging version of this site and rechecked/resaved the settings and this site still didn't autocomplete. However I had a bit of a light bulb moment and dug a little deeper, and it seems to be related to the [Select2 module](https://github.com/backdrop-contrib/select2).

 - Related: https://github.com/backdrop-contrib/select2/issues/10

**Comment by bugfolder** [comment]
Renamed the issue to make it clearer to someone browsing issues what the problem relates to.

**Comment by argiepiano** [comment]
I'm not able to reproduce this problem. The autocomplete is working fine for me
1. I set up the files path at admin/store/settings/products
2. I uploaded files at admin/store/products/files
3. After that the autocomplete node/17/edit/features/file/add (for example) worked

I don't have the Select2 module in this site, so maybe the problem is there?

One thing I did notice is that Ubercart has a completely separate system for files - these files will not appear in the standard Backdrop Manage files page. Perhaps this is by design, since for sale files should generally not be accessible?

**Comment by bugfolder** [comment]
> Perhaps this is by design, since for sale files should generally not be accessible?

It's definitely by design, because the access control for these files is entirely different from D7 & B's access control for private files; the latter is based on permissions associated with roles, while Ubercart maintains its own access control based on individual identities—for example, whether you purchased the product that the file is attached to. (It's also possible for additional modules to add/remove files from a user, using (for example) `uc_file_user_renew()` to add a file.)

**Comment by bugfolder** [comment]
Going through Ubercart issues: @laryn, is this still a problem in current Ubercart?

**Comment by laryn** [comment]
I think we can close as the site this occurred on was using Select2 and I think it was an issue from that side.

**Comment by nattywebdev** [comment]
I have just come across this issue when attempting to add  downloadable file to a product as a feature.

I have Select2 enabled on the site and have now disabled the Select2 option

``Use Select2 for elements with autocomplete (e.g. Tags)`

and the autocomplete now works as expected.
