### ISSUE TITLE
Price not updating when selecting attribute options

### ISSUE THREAD

**Issue by john-haus** [backdrop-contrib/ubercart#286]
It's been a while since I last used Ubercart, but isn't the display price supposed to update when making attribute selections that affect the cost of a product?

**Comment by john-haus** [comment]
follow up: the issue appears to be that the config file is not being updated correctly.  If you go to dmin/store/settings/products and check "Update product display based on customer selections" , this selection is not being saved to the config file. The same goes for " Display an optional quantity field in the Add to Cart form."

After manually editing the config file, the price is updating after attribute selection

**Comment by bugfolder** [comment]
I confirm this behavior. Looking into it.

**Comment by bugfolder** [comment]
OK, found the root cause (and another related bug).

In the new Backdrop world of config, to use `system_settings_form()`, we need to set `$form['#config']` to the appropriate config file, which `uc_product_settings_form()` does, to `'uc_product.settings'`.

However, two implementations of `hook_form_FORM_ID_alter()`, namely `uc_attribute_form_uc_product_settings_form_alter()` and `uc_product_kit_form_uc_product_settings_form_alter()` change the value of `$form['#config']` to their respective config files (`'uc_attribute.settings'`) and `'uc_product_kit.settings'`, respectively). So when `system_settings_form_submit()` gets called, it stuffs everything in the last config file that got overwritten in `$form`. (Currently, it's ending up in `uc_product_kit.settings.json`.)

The solution appears to be to give `uc_attribute` and `uc_product_kit` their own submission functions to handle their own variables and not try to take over `system_settings_form()`. So that will take a little work to implement, but I'll work on it.

Thanks, @padprint, for flagging this!

**Comment by bugfolder** [comment]
It occurs to me that another possibly simpler solution would be for `uc_attribute` and `uc_product_kit` to just store these settings in `uc_product.settings`, and then be careful to clean up `uc_product.settings` upon deinstallation.

**Comment by bugfolder** [comment]
After further investigation, that's not simpler; too much code already assumes those variables are stored in their respective modules' config files. So the best solution is to have each module store its own config variables explicitly from the form, rather than trying to rely on `$form['#config']`. PR to follow.

**Comment by bugfolder** [comment]
The updated PR now adds changes to uc_file, uc_roles, uc_attributes, and uc_product_kit modules to more cleanly handle how those respective modules store their config settings from the product settings form at admin/store/settings/products.

Also added is a field for a missing variable for uc_file: `uc_file_file_mask`. If this variable didn't happen to be set, there was no way to set it to its correct value.

Previous problems with storing config variables resulted in variables being stored in the wrong config files, so there are some new update functions that clean up config files to eliminate misplaced and/or superfluous variables.

**Comment by john-haus** [comment]
Quick test shows this now working. Thanks for the speedy resolution!
