### ISSUE TITLE
Notice: Undefined index: total in theme_uc_cart_review_table()

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#302]
Reported in https://github.com/backdrop/backdrop/pull/3848 by @argiepiano:

- Create a Product
- Add product to cart
- Visit the cart and click "Checkout" (important: do not click "Update cart" before "Checkout")
- The following notices appear when the checkout page is displayed:
`Notice: Undefined index: total in theme_uc_cart_review_table() (line 530 of /Users/alejandrocremaschi/Sites/localhost/bdentity/modules/ubercart/uc_cart/uc_cart_checkout_pane.inc).`
The Cart Contents table doesn't show any product or prices. This doesn't happen if you test using a version of Backdrop without this PR.

From @herbdool:

The method there doesn't even match entity_plus (see https://github.com/backdrop-contrib/ubercart/blob/54cd60913c411b0eff0eef759da7bbafa3890e48/uc_order/uc_order.controller.inc#L71), it's passing a `$content` variable back which doesn't appear in `entity_plus`. So it needs to get fixed there. Likely just adding the array to $product->content and returning it is enough.

From @argiepiano:

The ubercart `buildContent` method does match the corresponding method implementation in Entity Plus - [see it here](https://github.com/backdrop-contrib/entity_plus/blob/4b5de214e6f4b8a58deb9f311a16cb796a879cf8/includes/entity_plus.controller.inc#L634). The `$content` variable was a way to pass content to the method - and in ubercart's case, to the parent. Still, I don't think the issue I found lies there.

**Comment by argiepiano** [comment]
I must add that this issue is only present when the PR https://github.com/backdrop/backdrop/pull/3848 is applied to Backdrop. This PR adds the following to Backdrop's core:

- Adds methods `buildContent` and `view` to `Entity` and `DefaultEntityController` (and also to all core entity controllers like `NodeStorageController` etc
- Adds functions `entity_view`, `entity_view_multiple` and `entity_build_content` to core

These were modeled on Entity Plus, but there are some differences (e.g. on the arguments the functions use, and the array structure that entity_view returns). 

I can try and help figure out why this issue is happening... in a few days.

**Comment by bugfolder** [comment]
So, I've tried this with the 1.21-preview version (that includes https://github.com/backdrop/backdrop/pull/3848) and I get several problems of this sort, including an error:

* Error: Unsupported operand types in uc_taxes_entity_plus_view_alter() (line 149 of /webroot/modules/contrib/ubercart/uc_taxes/uc_taxes.module).

And also several notices like

* Notice: Undefined index: total in uc_taxes_entity_plus_view_alter() (line 148 of /webroot/modules/contrib/ubercart/uc_taxes/uc_taxes.module).

All the errors I'm seeing are in uc_taxes.module.

**Comment by bugfolder** [comment]
Disabling uc_taxes module eliminates the error (but we'll have to go back and check on that) and now I see the errors that you report above.

**Comment by argiepiano** [comment]
Hmm... this may be the result of the changes in core. 

As I mentioned above, the array structures that the new functions return are different, and since Entity Plus extends `Entity` and `DefaultEntityController` there is a chance that the new methods in core are running if they have not been overridden. I know this was the case with one of my modules. I had to purposely override `buildContent` in one of them to match the old array structure. 

I'll try to take a look later tonight.

**Comment by bugfolder** [comment]
Also, as I mentioned in the Zulip thread, many of the Ubercart tests are now failing. You'll need to apply https://github.com/backdrop-contrib/ubercart/pull/301 to get them to all pass under Backdrop 1.20.3, but upgrading core to 1.21-preview tanks several of the automated tests.

**Comment by bugfolder** [comment]
Yeah, I've rolled my core back to 1.20.3, but I'm still seeing the failing tests (again, same tests). Using the dev version of Entity Plus. I think my prior tests were also using the dev version of Entity Plus. (Also of Rules.) I swear I had it all green when I tested [301](https://github.com/backdrop-contrib/ubercart/pull/301)!

**Comment by argiepiano** [comment]
I have confirmed that the issue reported here happens only with B 1.21.0-preview, and doesn't seem to be related to Entity Plus dev. Will continue testing

**Comment by argiepiano** [comment]
I found the issue. It's quite complex, and it's related to the new `Entity::buildContent()`. Ubercart has some poor coding that creates this issue in 1.21.0. Let me walk you through this. 

I've reduced this to the simplest form: only a single product placed in the cart.

1. When you put a product in your cart and click "Checkout" Ubercart invokes `theme_uc_cart_review_table` to show you the review table. `$variables['items']` contains a `UcCartItem`, which is an entity of type `uc_cart_item`. This is important to remember.
2. Line 526 of `theme_uc_cart_review_table` calls `uc_order_product_view_multiple` to create a renderable array to display the item in the cart in the Checkout pane
3.  `uc_order_product_view_multiple` calls `entity_plus_view` and sends `'uc_order_product'` as the first parameter, which is the entity type. Of course, this is completely wrong, since the entity that it had received was of type `'uc_cart_item'`, not `'uc_order_product'`. This is very poor.
4. `entity_plus_view` stores the entity type variable in its property `entityType`. At some point it calls `entity_plus_build_content` and sends `entityType` (in this case `'uc_order_product'`) and the actual entity (which is actually of type `'uc_cart_item'`).
5. `entity_plus_build_content` checks if `Entity::buildContent()` exists. In B 1.20.3, this method did not exist, and therefore `entity_plus_view` proceeded to the `elseif` statement which was safe. It got the entity controller based on the `$entity_plus_type` variable it received (i.e. `'uc_order_product'`), and we are all happy, no errors. 
5. BUT in Backdrop 1.21.0, we DO have `Entity::buildContent()`, and therefore `entity_plus_build_content` invokes the entity's `buildContent` method.
5. Unfortunately `Entity:buildContent()` uses the ACTUAL type of the entity to get the controller. So, it ends up getting the controller for `'uc_cart_item'`. And then we get the error, since the renderable array we get back is completely wrong, as it's returned by the wrong controller.

Phew. OK, so what's the solution? This is tricky. You could write a `UcCartItem::buildContent` to override `Entity::buildContent` and use `UcOrderProductController`, but this is not ideal, as you don't want to get the wrong controller (sometimes we DO need to use `UcCartItemController`).

A slightly better solution is to modify  `uc_order_product_view_multiple` so that it actually sends a UcOrderProduct entity rather than a UcCartItem one to `entity_plus_view`.

But there may be better solutions. I'll think a bit more about this and will post a follow-up. Time for dinner.

**Comment by argiepiano** [comment]
There's more to this issue. There is an issue with the $order->products. The first time you access the checkout pane, it contains UcCartItem entities (wrongly). If you refresh the page, then it contains UcOrderProduct entities. This seems to be a bug in ubercart that went unnoticed until the changes in `Entity:buildContent`. 

TBH ubercart is quite a tangle of spaghetti. I'll try to figure out why the order gets attached cart items instead of order products when you first access the checkout pane. Solving that will solve the above.

**Comment by argiepiano** [comment]
And one more important piece of information: Drupal's ubercart presents the same issue about $order->products:  the first time you access the checkout page it contains cart items, when you refresh those have been changed to order products. And `Entity::buildContent` provided by Entity API looks exactly the same as the one in Backdrop 1.21.0. The crucial difference is that in Drupal, both, cart item entities and order product entities are stdClass, rather than its unique Entity API classes, and they don't extend `Entity` at all. Meaning that Entity API never calls `Entity::buildContent`.

So, at some point when porting Ubercart to Backdrop someone decided to create full-fledged entity classes for those entities, extending `Entity`... resulting in this issue we are seeing now.

Having all this information, I believe I can provide a solution that may be a bit "hacky" but may work. Hopefully tonight...

**Comment by argiepiano** [comment]
PR #303 . 

The solution: although it looks a bit hacky, this is the best I have come up with given the clunky architecture of the order creation on checkout: load the newly created order (which automatically attaches the UcOrderProduct array to it) before sending those products to   `uc_order_product_view_multiple`.  This solves the issue of the wrong controller being invoked and the wrong renderable array being returned to `theme_uc_cart_review_table`.

By the way, this doesn't affect in any way the rebuilt of orders if someone revisits the checkout page after adding or removing products, etc.

**Comment by argiepiano** [comment]
Well, it seems I spoke too soon. This "fix" still throws errors if you go back to your cart, remove an item and then checkout again. I will revise it tomorrow.

**Comment by argiepiano** [comment]
I found a somewhat hacky but elegant solution: transform all item objects passed  to `theme_uc_cart_review_table` into stdClass object. This doesn't affect the original order or uc_cart_item objects at all, since this is just done for displaying the review table.

This also follows the pattern used by Drupal's Ubercart, where the uc_cart_item objects were all stdClass (only when ported to Backdrop these objects became extensions of `Entity`).

This has solved this particular problem for me. I've checked all types of operation - emptying the cart, modifying quantity, adding more items, etc. It works fine.

@bugfolder , this may give you some clues into why taxes are causing issues (see especially my comment explaining the process that leads to the call of `Entity::buildContent` above).

I can take a look at taxes later.

EDIT: a quick explanation on how to transform objects into stdClass - simple typecasting:
`$stdclass_object = (object) (array) $original_object;`

This assures that the original objects are not altered in any way - they are made into arrays and then back into objects (stdClass this time).
