### ISSUE TITLE
USPS warnings

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ubercart#337]
I was looking at another issue on a site and noticed these warnings in the log (Ubercart 1.x-3.13.1):

> Notice: Undefined property: UcCartItem::$usps in _uc_usps_package_products() (line 825 of /app/modules/ubercart/shipping/uc_usps/uc_usps.module).

> Notice: Trying to access array offset on value of type null in _uc_usps_package_products() (line 825 of /app/modules/ubercart/shipping/uc_usps/uc_usps.module).

> Warning: in_array() expects parameter 2 to be array, null given in _uc_usps_package_products() (line 728 of /app/modules/ubercart/shipping/uc_usps/uc_usps.module).

**Comment by argiepiano** [comment]
Not sure if this may fix this exact problem, as I'm not able to reproduce completely, however, I do see the third warning, which is caused by a null `$addresses` variable (should be an array) being passed to `_uc_usps_package_products()`. 

This is caused by some faulty code [here](https://github.com/backdrop-contrib/ubercart/blob/6d5df33dac77f36252be2e2894f802a9ae808cc0/shipping/uc_usps/uc_usps.module#L319), where the function is invoked without defining `$addresses`. 

Will provide a PR shortly.

**Comment by argiepiano** [comment]
PR submitted. This PR passes a correctly built array of addresses for the products. In my intallation, this took care of the third warning in the OP, which appeared when an address was entered during the checkout process. Please test to see if this fixes the other warning?

**Comment by bugfolder** [comment]
The PR looks good to me, but I think we should get @laryn to test it under the conditions that produced the warnings.
