### ISSUE TITLE
Make the "My order history" title dependent on the current user's role

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/ubercart#341]
While "My order history" is good for the client user himself/herself, for admin browsing another person's order history the title should be something like "@username's order history".

**Comment by bugfolder** [comment]
This can be accomplished via the Views UI by setting the title of the page in the `uc_orders_user` View to `%1's order history`. `%1` is the replacement pattern for the username.

The question is, should we make this a permanent change in Ubercart, or just rely on people who want this title instead of the default editing their `uc_orders_user` View? (And if we do change it, should it be `%1's order history`, or `%1: order history`, or something else?

**Comment by argiepiano** [comment]
I think it would make sense to make that a permanent change in Ubercart. I'm not sure the `%1's order history` would work well for translations (the added 's). So perhaps `%1: order history`?

**Comment by bugfolder** [comment]
> So perhaps `%1: order history`?

Agreed, implemented.

**Comment by argiepiano** [comment]
This works fine. A couple of points: this will only work for new installs of Ubercart. Existing installations will not change the View title, unless the file `views.view.uc_orders_user.json` is manually moved to the files/config_XXX/active folder (losing all customizations). I'm not sure it's worth creating an update hook for such a small change, though.
