### ISSUE TITLE
Undefined property: Node::$model in uc_stock_entity_update()

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#362]
This problem arose in a custom module in which a Node of a different type is converted to an Ubercart product node. At the time of conversion, this error is generated:

```
Notice: Undefined property: Node::$model in uc_stock_entity_update() (line 133 of /.../modules/contrib/ubercart/uc_stock/uc_stock.module).
```

which happens because the original node type doesn't have a `->model` property. We can eliminate the error (and slightly more bulletproof the code) by checking for the existence of the `model` property prior to trying to update the stock table.

PR to follow.

**Comment by argiepiano** [comment]
I'm not sure this is the best approach. I believe the `model` property is actually the sku of the product - all products should have it. It's stored in the table `uc_products` along with other node product properties, and gets added to the node when the node is loaded. While the patch may fix the error, it may actually create other problems. In short, the notice is a symptom of a bigger issue: the product is faulty because it does not have an entry in `uc_products`. 

So, a better solution is to properly convert your other node type into a product node. Relevant functions are `uc_product_prepare()`, which adds default (empty) product properties to the node before invoking the node product edit/save form, and `uc_product_insert()` and  `uc_product_update()`, which write a record to `uc_products`.

Ideally, your conversion functions should make those calls as well.

**Comment by argiepiano** [comment]
Model is a required property of products - they all should have one.

<img width="329" alt="Screen Shot 2022-08-16 at 8 14 20 AM" src="https://user-images.githubusercontent.com/9938978/184901878-e5354cae-d4a7-4a51-9de1-3e936db7c061.png">

**Comment by bugfolder** [comment]
Thanks for the suggestions, agreed on the approach. Closing this.

**Comment by bugfolder** [comment]
Just a final wrapup note: the problem was that since the previous node (a "product submission" node) wasn't a product type (by design), it didn't have a `model` field so that `$entity->original->model` didn't exist when the entity controller called it up from the db. (The `model` field was already getting created properly as part of the conversion routine.) But adding a dummy `$entity->model = ''` to the original via `hook_entity_load()` did the trick, so no Ubercart modification needed.
