### ISSUE TITLE
Error: Call to undefined function uc_store_email_from()

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/ubercart#366]
I'm getting this error on a Simplo site with all the modules enabled for testing. Not sure of cause yet, but open to ideas on how to help debug this. 

I tested and am getting this error with no Ubercart sub-modules, only the core ubercart module. But, lots of other modules.

```
Error: Call to undefined function uc_store_email_from() in uc_cart_default_rules_configuration() 
(line 39 of /var/www/..../modules/contrib/ubercart/uc_cart/uc_cart.rules_defaults.inc).
```

![image](https://user-images.githubusercontent.com/3144571/192723008-bd279ab8-28bc-4ba1-915c-afe3deb251fa.png)

**Comment by argiepiano** [comment]
Enabling the module `ubercart` should automatically enable a few other required modules, including `uc_store` which is where that missing function lives.

My guess is that somehow, `uc_store` got disabled, or couldn't be enabled in the first place. You can try disabling and enabling ubercart again, then check watchdog for a system message confirming `uc_store module enabled` or otherwise an error.

A quick and dirty way to check if `uc_store` is enabled is to edit `uc_store.info` and commenting out `hidden = 1`, then clearing the cache. Then go to Functionality > List module and look for "Store" under Ubercart. Check if it's disabled or enabled after the above (should be enabled) and report here. If it's disabled, your site has a problem enabling it for some reason.

**Comment by argiepiano** [comment]
OK, addition to the above. Since your site is giving a fatal error, you can't probably do what I suggest above (disabling and enabling ubercart).

You may need to disable it with `bee` or `drush` (may not work if the site needs to boostrap), or force disable ubercart by editing the database... or use a backup you made before enabling ubercart. Let me know if you need help with that. Those kinds of fatal errors are hard to fix since you can't use the Backdrop UI anymore.

**Comment by stpaultim** [comment]
@argiepiano - The good news is that I encountered this problem on a test site while experimenting. I had just tried to enable a whole bunch of modules all at once and I am speculating that maybe something interrupted the enabling process before it had enabled the store sub-module. 

I am able to start over and try this again, but so far have been unable to recreate this problem. So maybe it was a fluke. I'm inclined to close this issue for now and reopen it if I am successful at recreating the problem.
