### ISSUE TITLE
Expose attributes to views

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/ubercart#403]
Like written here: https://www.drupal.org/project/ubercart/issues/895236 - having the ability to use attributes within views (e.g. to export a range of orders as csv file with attributes as separate fields) would be great.

I don't know whether the D7 patch works and could be ported.

**Comment by bugfolder** [comment]
Looking into this. The patch will need some changes for Backdrop compatibility, and [Comment 114](https://www.drupal.org/project/ubercart/issues/895236#comment-13750511) raises some issues that warrant further investigation.

**Comment by bugfolder** [comment]
I've ported the patch and filed a first PR (that seems to work), but still TBD are the inefficiencies noted by philsward in https://www.drupal.org/project/ubercart/issues/895236#comment-13750511.

**Comment by argiepiano** [comment]
This is a complex task because of the way attributes and options are handled in Ubercart. `uc_order_product` entities store attributes and options in a "literal" manner  (in the `data` column of the `uc_order_products` table)  rather than as a reference to an existing attribute and option(s). This is done so because there is the danger of an attribute or an option being modified after a product has been paid for. The customer, when looking at past orders, needs to see the name of the attribute and option as they were at the moment of ordering the product, not the new names after those are potentially modified. This whole way of handling attributes is not very robust. It has the benefit of saving the site builder from the tedious task of creating 9 different products for a single item that has 3 attributes with 3 options each, but at the same time it  makes the task of providing Views fields and filters for order product attributes and options very, very tricky.  

I think all the points in the linked comment are valid. Some of them are easy to fix. To me the most worrisome aspect is the fact that we are creating separate field handlers for every combination of attributes and their option (if you have 4 attributes with 10 options each, that's 40 field handlers).  In addition, if the options are changed later (e.g. option ID number 3 changes from "Blue" to "Light blue"), you'll get some false hits (products with oid 3 will all show up, regardless of whether they were "Blue" or "Light blue" when they were purchased). This is an unavoidable limitation.

In addition, regardless of this limitation, and without having given this much thought: in order to avoid creating 9 individual field and filter handlers for 3 attributes with 3 options each (which is what this code does), I'm wondering if a model similar to the one used by webform's `webform_submitted_data` would work for attribute -> options. Like webform, all attribute options are stored in a single table under two ids: aid (attribute ID) and oid (option ID). So perhaps there is a way to create one handler per attribute, and then have a UI where you can select the option for filtering.

**Comment by argiepiano** [comment]
And another limitation: if an option or attributes are deleted later, the current handler has no way to filter past purchased products that used those.

**Comment by argiepiano** [comment]
A (useless) side note: Drupal Commerce dealt with these limitations in a slightly more robust way: product variations were stored in the line item entity through Field API fields, for example as List (text) fields. The Field API handling is more robust, in that it won't let you delete an option if it's being used by any line item entity instance in the db. On the other hand, if you did change the label for an option of the field, it would change also when viewing the order in the future.

**Comment by bugfolder** [comment]
Good food for thought. In the meantime, I've updated the PR with improved efficiencies in the db queries (but using the existing logic, subject to the issues you just described).

**Comment by argiepiano** [comment]
@bugfolder thanks for this! The fixed issues in the comment look good. I left some comments in the PR.

I believe there is a more efficient way to provide field handlers for attribute/options without defining handlers for each combination of attr/option. I'll take a crack at it tomorrow. Also, I think the same for the attribute filters - there may be a more efficient way to do that without defining a handler for each attribute.

**Comment by bugfolder** [comment]
> I believe there is a more efficient way to provide field handlers for attribute/options without defining handlers for each combination of attr/option. I'll take a crack at it tomorrow.

Overnight I thought that it should be possible to provide a single field handler that takes the attribute and option as a setting, so that if a person really wants to see all 3x3 possible combinations, they'd just add the 3x3 instances of that one field to their View with different settings. Is that what you were thinking?

**Comment by argiepiano** [comment]
> Overnight I thought that it should be possible to provide a single field handler that takes the attribute and option as a setting

That's what I had in mind

**Comment by bugfolder** [comment]
> I'll take a crack at it tomorrow. ... provide a single field handler that takes the attribute and option as a setting [is] what I had in mind

OK, I'll hold off on doing this in favor of you to avoid duplication of effort (but if you've got better things to do, I'm pretty sure I can build it).

**Comment by argiepiano** [comment]
@bugfolder go ahead and give this a try. I'm traveling all day today. Thanks!

**Comment by argiepiano** [comment]
I've looked into this a bit. 
- The field handler definitions can be done more efficiently as discussed above, by creating a generic field handler for attribute/option pairs for each of the desired columns (price, cost, weight), and having a UI element in the Views field configuration to choose the attribute/option to display. The way this is done in the ported PR is wasteful in that it defines a separate field handler for each combination, just for the purpose of displaying the proper field/column title in the Views output. 
- The filter handler is trickier. Because options are stored in the `data` column as a serialized string, the ported PR actually uses a "hack" to filter values. For example, if your option has oid = 5, the filter will add a WHERE clause for the column `data LIKE %i:5;%`, basically looking for the portion `i:5;` in the serialized `data` column. This is prone to errors if you have other modules that happen to store the integer "5" somewhere in the `data` column as well

So, the filter is problematic because of design issues. In the long run, a "proper" way to solve this would be to modify the way attribute options are stored per ordered product. Instead of using a serialized string in an omnibus `data` column, they should be stored in their own table. 

Perhaps we can create a contrib module for the time being that creates such as table (it would also need to populate that table with existing data upon installation, as a batch process). Once that table is created, handling the Views fields and filter should be more robust.

**Comment by bugfolder** [comment]
I started on this, then other things intruded, so I'm happy to pass the baton back to you on this particular issue. I basically agree with your analysis (of course!), expecially about replacing the serialized string data with a proper table.

I'd be nervous about adding the hacky filter to Ubercart core, because that somewhat commits us to keeping things the way they are (serialized string). Whereas putting the filter in a contrib module (`uc_attribute_views`?) makes it a little easier to contemplate changing Ubercart core as it evolves (although we'd still have to coordinate with the contrib module maintainers when it's time to change attribute handling).

**Comment by argiepiano** [comment]
@bugfolder just an update: I'm working on the custom module and making good progress. I'd love some testing when I have something ready (@djzwerg  and @bugfolder!)

**Comment by argiepiano** [comment]
I have released a new module, Ubercart Attribute Views, which provides several Views fields/filters related to UC Attributes and Options for products and ordered products.

It'd be wonderful if you could test! 

https://github.com/backdrop-contrib/uc_attribute_views

**Comment by bugfolder** [comment]
Brief examination, that looks great! I'm traveling for a while, so won't be able to test till Feb., but will do so.

**Comment by djzwerg** [comment]
I'm going to test it during the next week.

**Comment by djzwerg** [comment]
I made a few tests today and nearly everything works fine. One issue I've found is described [here](https://github.com/backdrop-contrib/uc_attribute_views/issues/2).

Thanks a lot for this fast development!

**Comment by bugfolder** [comment]
@argiepiano, with your https://backdropcms.org/project/uc_attribute_views (with several installs now!), should we close this issue as fixed?

**Comment by argiepiano** [comment]
Yes, thanks.
