### ISSUE TITLE
Deprecated function: Automatic conversion of false to array is deprecated in _uc_product_get_variant() (line 676...

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/ubercart#448]
In PHP 8.1, you get this warning when you view a product:

`Deprecated function: Automatic conversion of false to array is deprecated in _uc_product_get_variant() (line 676 of /Users/XXX/Sites/localhost/XXX/modules/ubercart/uc_product/uc_product.module).`

The issue is that `$node->data` before line 676 has FALSE value.  `$node->data` is set by the User module (and possibly others) in `user_node_load()`. The User module sets it to a serialized string, which is often `b:0;` (i.e. empty), resulting in `false` when `uc_product` unserializes it.  

So, PHP 8.1 complains when line 676 assigns `$node->data['module'] = 'uc_product'` as an array (since it was `false` before). 

The solution is to check and see if `$node->data` is empty and is not an array right after unserializing it, and if so, make it an empty array. There may be other more elegant solutions, but this works too.

PR coming

**Comment by argiepiano** [comment]
PR #449 ready for testing an review.

**Comment by bugfolder** [comment]
* Verified the problem under PHP 8.1.
* Verified that the patch fixes the problem under PHP 8.1.
* Verified that it doesn't introduce any problems under PHP 7.4 (not that any were expected).
* Reviewed code; looks good.

So, RTBC.

I wondered if it could every be a serialized something-other-than-an-array, but since user module "owns" that field and always sets it to an array (the result of a `fetchAllAssoc()`), any other module would have to respect that.
