### ISSUE TITLE
Undefined property: BlockLegacy:

### ISSUE THREAD

**Issue by andreazk** [backdrop-contrib/ubercart#453]
Notice: Undefined property: BlockLegacy::$subject in uc_catalog_preprocess_block() (line 318 of /app/backdrop/modules/ubercart/uc_catalog/uc_catalog.module).

Hi - I have installed backdrop with ubercart on lando and configured a store and a few products.  I keep seeing this error message. Any ideas? Thanks

**Comment by argiepiano** [comment]
Thanks for reporting. This is a bug. I'll provide a PR in a few minutes.

**Comment by argiepiano** [comment]
@bugfolder this is a bit more complex than it seemed:

- The preprocess function is retrieving the subject from the block using the wrong property (the subject is inside `->content['subject']`, not `->subject`)
- That property is private and can't be fetched or set, so this is also wrong.
- The things that the preprocess function is doing can be easily done in `uc_catalog_block_view()` [head scratcher]: the code is trying to link the title of the block to the catalog browsing page
- HOWEVER: this opened a new whole can of warms. The view `uc_catalog_terms` is defective. It has a defective preset vocabulary filter that uses a numerical id instead of a machine name, as all vocs in Backdrop. 

So, what I'm proposing:
- Fix the uc_catalog_terms view with the correct voc
- Move the subject linking code to uc_catalog_block_view()
- Remove the preprocess function

This will take me a bit (I'm out for a couple hours). Let me know if you have any thoughts, or want to wait until I have a PR :)

**Comment by argiepiano** [comment]
@andreazk in the meantime, just remove the catalog block from your layout

**Comment by bugfolder** [comment]
This sounds plausible, so please proceed with the PR (and thanks for the quick jumping-on-it and identifying-of-worms).

**Comment by argiepiano** [comment]
It gets a bit more complicated: so, the user can override the title of the block in the block config UI. But the overridden title is not available to `uc_catalog_block_view()`. So, that's why this was being done in the preprocess function, once the title was already known - but of course the issue is that you can't change the block title property in the preprocess function, since it's a private property.

So, the solution to retain all this functionality is to extend BlockLegacy to create a custom class that does all the linking. I'll attempt this today.

**Comment by argiepiano** [comment]
... I meant, extend `Block` (not `BlockLegacy`). In other words, avoid using hooks to set the content and title, and instead do it the "Backdrop way" through the class.

**Comment by andreazk** [comment]
Hi, thanks for looking into this!  I have a few other suggestions, but I am new to backdrop.  Let me know if there is a better place (than the issue queue) to help with ubercart module/ test code,  etc.

**Comment by argiepiano** [comment]
Hi @andreazk. This is the best place to contribute and collaborate with Ubercart. I'd love to hear your suggestions. You may also want to participate in the [Zulip chat](https://backdrop.zulipchat.com/) for Backdrop.

**Comment by argiepiano** [comment]
@bugfolder, @andreazk, I have provided a PR that fixes this. #454
 
This PR is pretty substantial and requires some explanations:

First the easy stuff:
1. I moved all the catalog block functionality to a class. This allows us to make the block title into a link to the catalog page , which was the original intention of the preprocess function
2. I removed all block hooks (except the info one) since they are not needed
3. I fixed the catalog terms view with the defective filter 
4. I created an upgrade hook to fix the installed defective view, IF if hadn't been fixed before (only the default display, since one would assume if someone created a new display already realized that the filter was defective, as the view could not be saved if not fixed)

Now the trickier stuff:

So, the code as it was, had an interesting mix of config and block functionality. The catalog block settings form saved the block settings into a config (!!!!) and used that config file to process and created the term tree to be displayed in the block. Which meant, every time you created a new catalog block, you wiped out the configuration from the older catalog blocks. This meant that you couldn't have one block that create the catalog link in one layout, and another that did not created it in another layout. The tree building function would always use the config file settings, which always matched the configuration of the latest block to be created.

So, I have removed this problem. Now the tree building ALWAYS follows the actual configuration WITHIN the block, not the one in the config file. This meant modifying the theming function for the term tree.

Things I haven't tested (run out of time)
- Will these changes need another upgrade hook to inherit the old block settings? I don't think so, but haven't tested
- I just thought that three settings in `uc_catalog.settings` are not needed with these changes `uc_catalog_expand_categories`, `uc_catalog_block_nodecount` and `uc_catalog_expand_categories` as the code now uses those from the saved block settings.  I need to remove those. 

So I ran out of time and will need to address this last one tonight.

**Comment by argiepiano** [comment]
@bugfolder I've pushed a couple more changes. I did have a chance to test updating a site that had a block from the previous version. I had to add another update hook in order to move the settings, which, in the old code were stored into `$block->settings['block_settings']` (which is a default location when no submit handler exists for the block settings form), and moved them to the root of settings, in `$block->settings`, which is the standard location where blocks save custom settings. 

Please give it a try. @andreazk, to test, you can download the patch file at 
https://patch-diff.githubusercontent.com/raw/backdrop-contrib/ubercart/pull/454.diff
Put the file in the ubercart folder and them  in the terminal (shell command) run `patch -p1 <FILE_NAME`

**Comment by bugfolder** [comment]
OK, I'll try tomorrow on a local version of my UC site.

**Comment by andreazk** [comment]
Thank you so much @argiepiano and @bugfolder. I will install the patch tomorrow and let you know how it works.

**Comment by andreazk** [comment]
hi, run command not found, probably best if done with lando, but no documentation on installing backdrop patches.  Maybe just by hand with vi, I guess.  Traveling this weekend, will try again next week.

**Comment by bugfolder** [comment]
I've tried this out on an existing site, and all works well. `uc_catalog_terms` was already updated, so the upgrade functionality of views-fixing wasn't tested by that, but all else works. LGTM.

Also looks like it's time for another release with the existing RTBC PRs.

**Comment by andreazk** [comment]
Hi, sorry for the delay, traveling.  I did a  lando rebuild, lando restart, saved the file to 454.diff and ran  patch -p1 <454.diff and it worked! Thank you!!!
