### ISSUE TITLE
Error in UC PayPal IPN response

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ubercart#467]
Just upgraded a site to PHP 8.1, and this error started appearing in watchdog:

TypeError: array_key_exists(): Argument #2 ($array) must be of type array, stdClass given in uc_paypal_ipn() (line 85 of /mysite/modules/contrib/ubercart/payment/uc_paypal/uc_paypal.pages.inc).

The relevant lines of code are:

```
  // TODO: Change this to property_exists when we have a PHP requirement >= 5.1.
  if (array_key_exists('error', $response)) {
    watchdog('uc_paypal', 'IPN failed with HTTP error @error, code @code.', array('@error' => $response->error, '@code' => $response->code), WATCHDOG_ERROR);
    return;
  }
```

Since Backdrop has a PHP requirement >= 5.1 (PHP 5.6 is minimum supported version), we can/should now make that change `array_key_exists('error', $response)` --> `property_exists($response, 'error')`.

**Comment by bugfolder** [comment]
BTW, after making this change on my production site, IPN transactions are going through again.

**Comment by argiepiano** [comment]
Hi @bugfolder. Thanks for this.

I'm wondering if `property_exists()` is the best approach here. If `backdrop_http_request()` ever returns an object with an empty property `error`, then this check will result in TRUE with the watchdog error created. I'm not sure if this situation ever happens (meaning a $response with an empty `error` property), but to be safer,  I'm wondering if simply checking with `if (!empty($response->error)) {}` might be better. This will only result to TRUE if the property error contains a string or numbers other than 0; on the other hand it will result to false when `error` doesn't exist, or when it's empty.

**Comment by bugfolder** [comment]
I tried to keep the logic the same as before (your points apply equally to when `array_key_exists` worked with older versions). In this case, PayPal's IPN is never supposed to return an empty `error` property, so would the situation ever arise where it makes a difference?

**Comment by bugfolder** [comment]
[Previous comment deleted; not well thought out. Further thoughts to follow.]

**Comment by bugfolder** [comment]
Are there any situations where `backdrop_http_request()` would return a set but empty `error` property? It looks like it always sets it with a specific string, except for the last possibility of setting it to `$result->status_message`. Can that ever be empty?

**Comment by acremaschi** [comment]
You are right that `error` is not set unless there is an error (the docs actually state that). My only hesitation here is that it is possible for Backdrop to use an alternate http system (you can see that `backdrop_http_request()` checks for that. With the trend of using full-fledged classes (rather than `stdClass`) and the trend of declaring properties, it may be remotely possible that an alternate http system may use a return response class that contains a pre-declared, null `error` property, and thus this check would return TRUE.

HOWEVER, looking at other instances of response checks in core (e.g. in `_update_process_check_task()`) I see that the common way of checking for errors is `if (isset($response->error)) {}`, so I'd say your approach is in sync with those cases (although I do think `property_exists()` is more easily and commonly replaced with `isset()`).

**Comment by argiepiano** [comment]
You are right that error is not set unless there is an error (the docs actually state that). My only hesitation here is that it is possible for Backdrop to use an alternate http system (you can see that `backdrop_http_request()` checks for that). With the trend of using full-fledged classes (rather than `stdClass`) and the trend of declaring properties, it may be remotely possible that an alternate http system may use a return response class that contains a pre-declared, null `error` property, and thus this check would return TRUE.

HOWEVER, looking at other instances of response checks in core (e.g. in `_update_process_check_task()`) I see that the common way of checking for errors is `if (isset($response->error)) {}`, so I'd say your approach is in sync with those cases (although I do think `isset()` is typically preferred over `property_exists()`).

[EDIT]: responded from the wrong account! Delete and re-posted.

**Comment by bugfolder** [comment]
So, if we allow for the emptiness of `$response->error`, it seems like our error message `watchdog('uc_paypal', 'IPN failed with HTTP error @error, code @code.', array('@error' => $response->error, '@code' => $response->code), WATCHDOG_ERROR);` would be malformed. Do we try to accommodate that, or just rely on the admin seeing a mucked-up watchdog message to know that something is amiss?

**Comment by argiepiano** [comment]
Actually, my point is that `$response->error` may be set (may exist), but be empty when there are no errors, if an alternate "http system" is used.  So, I was suggesting that we checked for `if(!empty($response->error)) {}` to detect errors, instead of `if(property_exists($response->error)) {}`.

**Comment by bugfolder** [comment]
Ah, OK. I added a comment to explain the logic for the benefit of future code-reviewers (or future "me").

**Comment by argiepiano** [comment]
LGMT!
