### ISSUE TITLE
Review order page styles don't match rest of theme

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/ubercart#508]
The styling on the Review Order page doesn't quite match the rest of the theme. It's quite narrow; the font is unnecessarily small and so on.

Before:

![2024-10-29 15 27 49 bd3 lndo site ecc72be91514](https://github.com/user-attachments/assets/0a432c41-f0c2-489f-a1fe-bf2055b21acb)

After:

![2024-10-29 15 44 54 bd3 lndo site 30a17375a004](https://github.com/user-attachments/assets/f71ad38f-ba37-42ae-8f0a-6620c93b5767)

**Comment by herbdool** [comment]
@bugfolder what do you think of this PR?

**Comment by argiepiano** [comment]
I think this look was an outdated attempt (probably in screens with lower resolution in the late 2000s) to make it look like a cashiers receipt. It's annoying and outdated, and it looks bad on modern screens. I'm all for changing this.

**Comment by bugfolder** [comment]
I definitely like the new look.

When I tried it on an existing site, I didn't get a full-width listing (even after flushing all caches and flushing the browser CSS/JS cache).

Before:

![before](https://github.com/user-attachments/assets/f3938065-55c6-40ab-9f35-36d467e7940d)

After:

![after](https://github.com/user-attachments/assets/043959e1-5a6b-4283-8116-4df9830acea6)

Adding `width: 100%;` to the `table` CSS gets it out to the full width, but the huge horizontal gap and tight vertical spacing actually degrades readability, IMHO.

![wider](https://github.com/user-attachments/assets/0c3b206b-9a00-41cf-adc3-254768f71c40)


Personally, I'm fine with tweaking the CSS on the site to get that table readable (since it has a unique class of `order-review-table`, it's easily targetable). While I do like the improvement shown above, I'm a little concerned about substantially changing the CSS on our users who may have made their own CSS overrides that don't play nicely with the updated CSS, and being surprised that the review page changes in potentially not a good way. Thoughts?

**Comment by herbdool** [comment]
What theme are you using? I guess some smart defaults are still needed in some cases.

**Comment by bugfolder** [comment]
Base theme is [Bootstrap Lite](https://backdropcms.org/project/bootstrap_lite). Then there's a sub-theme, but the sub-theme doesn't do much to the `order-review-table`.

We probably ought to check this against a bunch of common themes.

**Comment by herbdool** [comment]
Ah, ok. I noticed that the Review Order panes were being hardcoded into a table, rather than using a renderable array. So Bootstrap Lite couldn't inject its classes. So I've rebuilt that. It's a bit more radical of a change, but I think it's worth it since it's now easier to make sure it looks nice across different themes.

Bootstrap Lite:

![2024-10-31 12 01 10 bd3 lndo site 168a9013c4ae](https://github.com/user-attachments/assets/f4983654-d5bc-4a73-ac9f-d1b10f435403)

Basis:

![2024-10-31 12 00 52 bd3 lndo site 21013752e615](https://github.com/user-attachments/assets/fcf2509c-ac62-46bf-9077-e0671ac79e0d)

I also moved away from making the whole thing a giant table so now it's fieldsets with a table in each one.

> I'm a little concerned about substantially changing the CSS on our users who may have made their own CSS overrides that don't play nicely with the updated CSS, and being surprised that the review page changes in potentially not a good way.

One approach would be to change the classes so that any custom css overrides won't mess with the new look.

Another would be to try to make the fieldsets look closer to the table of tables. Not sure how important that is. And won't really address any custom css overrides.

**Comment by bugfolder** [comment]
Much better:

![revised](https://github.com/user-attachments/assets/e50fb36a-4a01-41a7-922e-e82ae6115ba7)

I particularly like that the "Review order" page stylistically matches the "Checkout" page, which helps the sense of continuity in the user.

I support this change.

**Comment by herbdool** [comment]
@bugfolder sounds good.

**Comment by laryn** [comment]
This is a good improvement.
