### ISSUE TITLE
empty product information on class creation page

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/ubercart#64]
When creating a new product out of a class, product information form is empty. No SKU, price, weight, etc fields can be defined.

**Comment by docwilmot** [comment]
Interestingly the fields are all there, just that a `display:none` is being applied to the fieldset. Even more interestingly, it seems this is because of the `#attributes` key in the form arrays with states on them. In other words, this doesn't work:
```
  $form['base']['weight'] = array(
    '#type' => 'container',
    '#attributes' => array('class' => array('uc-inline-form', 'clearfix')),
    '#states' => array(
      'invisible' => array(
        'input[name="shippable"]' => array('checked' => FALSE),
      ),
    ),
  );
```

But this will work:
```
  $form['base']['weight'] = array(
    '#type' => 'container',
    //'#attributes' => array('class' => array('uc-inline-form', 'clearfix')),
    '#states' => array(
      'invisible' => array(
        'input[name="shippable"]' => array('checked' => FALSE),
      ),
    ),
    '#weight' => 15,
  );
```
Same problem with the Product add form too: if you uncheck 'shippable', everything disappears.

This seems to be unique to Backdrop. Cant figure out why it happens. 

May be the easiest solution is to use `#prefix` and `#suffix` instead.
