### ISSUE TITLE
Cannot instantiate abstract class Entity in EntityDatabaseStorageController

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/ubercart#66]
Error message when adding a product to the cart:

```
Error: Cannot instantiate abstract class Entity in EntityDatabaseStorageController->create() (line 473 of /app/core/modules/entity/entity.controller.inc).
```

**Comment by docwilmot** [comment]
This is a core bug. See https://github.com/backdrop/backdrop-issues/issues/2558#issuecomment-295862718
It happens because of this block here in `EntityDatabaseStorageController`:
```
  public function create(array $values) {
    $class = isset($this->entityInfo['entity class']) ? $this->entityInfo['entity class'] : 'Entity';
    return new $class($values);
  }
```
If you provide an entity and it doesnt define an `entity class` in its `hook_entity_info()`, core defaults to instantiating `Entity` class (see code above), which is not allowed. 

Your `hook_entity_info()` implemenations need to define 'entity class'. See Entity Example Modue for example.

**Comment by robertgarrigos** [comment]
thanks @docwilmot

**Comment by robertgarrigos** [comment]
Solving this in #67
